# Generated by Django 5.2.4 on 2025-07-07 19:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50)),
                ('call_sign', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('tail_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='In Flight', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.FloatField(default=20000.0)),
                ('bearing', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='fleet.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='fleet.airport')),
                ('pilot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('target_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.pilot')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.plane')),
            ],
        ),
    ]
